
devices([
  "iPhone 8",
  "iPhone 13"
])

languages([
   "en-US",
   "de-DE"
])

scheme("SnapUITests")

output_directory("./screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

workspace "Networking.xcworkspace"

